/********************************************************************

       IMPORTANT: AUTO-GENERATED FILE - DO NOT EDIT!                 

 Generated by: cser-1.0.0
 Command line: -o spd_serializer -b raw -i ../spd_entry.h -v spd_entry_node 

********************************************************************/

#ifndef _spd_serializer_h_
#define _spd_serializer_h_
#include "../spd_entry.h"
#include <stdint.h>
#include <stdlib.h>
#include <sys/types.h>
#include <errno.h>
#include "serializer.h"


int cser_raw_store_struct_spd_entry_node (const struct spd_entry_node *val, cser_raw_write_fn w, void *q);
int cser_raw_load_struct_spd_entry_node (struct spd_entry_node *val, cser_raw_read_fn r, void *q);
int cser_raw_store_unsigned_long_long_int (const unsigned long long int *val, cser_raw_write_fn w, void *q);
int cser_raw_load_unsigned_long_long_int (unsigned long long int *val, cser_raw_read_fn r, void *q);
int cser_raw_store_unsigned_int (const unsigned int *val, cser_raw_write_fn w, void *q);
int cser_raw_load_unsigned_int (unsigned int *val, cser_raw_read_fn r, void *q);
int cser_raw_store_int (const int *val, cser_raw_write_fn w, void *q);
int cser_raw_load_int (int *val, cser_raw_read_fn r, void *q);
int cser_raw_store_unsigned_short (const unsigned short *val, cser_raw_write_fn w, void *q);
int cser_raw_load_unsigned_short (unsigned short *val, cser_raw_read_fn r, void *q);
int cser_raw_store_char (const char *val, cser_raw_write_fn w, void *q);
int cser_raw_load_char (char *val, cser_raw_read_fn r, void *q);
int cser_raw_store__Bool (const _Bool *val, cser_raw_write_fn w, void *q);
int cser_raw_load__Bool (_Bool *val, cser_raw_read_fn r, void *q);
static inline int cser_raw_store_spd_entry_node (const spd_entry_node *val, cser_raw_write_fn w, void *q)
{ return cser_raw_store_struct_spd_entry_node (val, w, q); }
#endif
