@startuml
Actor C as "CCIPS Controller"
participant S as "Sysrepo"
box CCIPS
participant sac as "spd_entry_change_cb"
participant sacl as "addSPD_entry"
participant rsa as "readSPD_entry"
participant sal as "add_spd_node"
database l as "init_spd_node"
participant pfa as "pf_addpolicy"
end box
participant K as "kernel"
autonumber
C -> S: Request install of SPD entry.
S -> sac: Notify about a change in the XPATH
sac -> sac: Identify that a new SPD entry is added
autonumber stop
sac -> sac: Identify SPD entry ID that has been added
sac -> sacl: Send SPD entry identifier (basically the name) + new xpath
autonumber resume
sacl -> sacl: Initialize an empty spd_entry_node 
autonumber stop
sacl -> rsa: Request the new spd entry, pass\nentire xpath and empty spd_entry_node)
rsa -> S: Request new spd entry by providing the entire xpath
S -> rsa: If entry exists forward the information
rsa -> rsa: Parse received information\nand fill empty spd_entry_node
rsa -> sacl: Return correct parsing
autonumber resume
sacl -> sal: Request to store new spd_entry_node
autonumber stop
sal -> l: Store spd_entry_node
autonumber resume
sal -> pfa: Request to install the\nspd_entry_node in the kernel
pfa -> pfa: Generate SADB_X_SPDADD message\nto add spd_entry_node
autonumber stop
pfa -> K: Install SPD_ENTRY
K -> pfa: Install confirmation
autonumber resume
pfa -> sal: Install confirmation
autonumber stop
sal -> sacl: Install confirmation
sal -> sac: Install confirmation
sac -> S: Install confirmation
S -> C: Confirmation of the installtion
@enduml