@startuml
box CCIPS RA
actor T as "Thread"
participant vsn as "verify_sad_nodes"
database l as "init_sad_node"
participant pfg as "pf_getsad"
end box
box CCIPS TA
participant hm as "handle_message"
participant hrvm as "handle_request_verify_message"
database lta as "trusted_init_sad_node"
end box
autonumber
T -> vsn: Request SAD entries verification
vsn -> l: Request stored SAD entries
activate vsn
note left
This is performed for each 
sad_entry_node stored in the init_sad_node
database
end note
autonumber 3.1
vsn -> pfg: Request information from the entry
autonumber 3.2
vsn -> vsn: Generate tmp sad_entry_node
autonumber 3.3
vsn -> hm: Send sad_entry_node in REQUEST_VERIFY_MSG
autonumber stop
hm-> hm: Identify and parse message
hm -> hrvm: Request verification of the sad_entry
hrvm -> lta : Request corresponding SAD entry
hrvm -> hrvm: Compare the two sad_entry_node
autonumber 3.4
hrvm  -> hrvm : Generate OP_RESULT_MSG with the result
autonumber stop
hrvm -> hm: Send OP_RESULT_MSG with the result
hm -> vsn: Forward result
autonumber 4
deactivate vsn
vsn -> vsn: Generate event
@enduml